In [1]:
import numpy as np

# Find the Even Numebrs

In [3]:
arr= np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## No need to run a loop to search each element to get the elements which are even elements and then it will filter based on which element fits in the formula , then it will return those elements which are extracted asnd saved into a different variable

In [4]:
boolean_index= arr%2==0
boolean_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [5]:
even_nums = arr[boolean_index]
even_nums

array([12, 14, 16, 18, 20])