# BROADCASTING ARRAYS , VECTORS , MATRIX , TENSORS

In [4]:
L= [10,20,30,40,50] # broadcasting array-1D, VECTRORS
import numpy as np
ADD= np.array(L)
ADD

array([10, 20, 30, 40, 50])

In [5]:
# broadcasting in numpy allows operations on arrays of different shapes.
# Here, we add 10 to each element of the array 'ADD'.
ADD + 10

array([20, 30, 40, 50, 60])

In [6]:
# bROADCASTING IN 2D ARRAY 
MAT = np.arange(1,26).reshape(5,5)
MAT

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [7]:
#broadcasting 2D array and ADD 10 to each element
MAT + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])