In [64]:
import numpy as np

# SHALLOW COPY

#### EXAMPLE 1 :-

In [65]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [66]:
slice = a[0:10]
slice

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
slice * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [68]:
slice

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [70]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [71]:
a[:6] * 10

array([10, 20, 30, 40, 50, 60])

In [72]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#### EXAMPLE 2 :-

In [73]:
b = np.arange(12,22)
b

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [74]:
b[:5]

array([12, 13, 14, 15, 16])

In [75]:
b

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [76]:
c= b * 10 # This will create a shallow copy, both 'a' and 'd' will point to the same data in memory
c

array([120, 130, 140, 150, 160, 170, 180, 190, 200, 210])

In [77]:
c[:3]

array([120, 130, 140])

In [78]:
c

array([120, 130, 140, 150, 160, 170, 180, 190, 200, 210])

In [79]:
c = b

In [80]:
b

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

### EXCEPTION CASE

##### Creating a copy of "a" and then changing its element using its indexing in "d" , it will change "a" also

In [81]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [82]:
d = a # This creates a deep copy of 'a'

In [83]:
d[0] = 999 # 'd' is a deep copy of 'a', so changing 'd' will also change 'a'
d

array([999,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [84]:
a # 'a' is also changed because 'd' is a deep copy of 'a'

array([999,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

# COPY() METHOD

In [85]:
# To avoid the deep copy issue, use the copy() method
e = a.copy()
a

array([999,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [86]:
e[0] = 555
e

array([555,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [87]:
a # 'a' does not change because 'e' is created using copy() method

array([999,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [88]:
# now after using copy() method, modifying 'e' does not affect 'a'
# as e[0] = 555 does not change a[0]

# DEEP COPY

#### EXAMPLE 1 :-

In [89]:
a1 = np.arange(1, 11)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
b1 = a1 # This creates a deep copy of 'a1'

In [91]:
b1[0] = 888 # 'b1' is a deep copy of 'a1', so changing 'b1' will not change 'a1'


In [92]:
b1 

array([888,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [93]:
a1 # 'a1' is also changed because 'b1' is a deep copy of 'a1'

array([888,   2,   3,   4,   5,   6,   7,   8,   9,  10])

# Excellent work! You've successfully explored the concepts of shallow and deep copies in NumPy arrays.