In [2]:
import numpy as np

# SPLITING ARRAYS
## SPLITING 2D MATRIX

#### HORIZONTAL SPLIT

In [3]:
a = np.arange(16).reshape(4,4)
a # Original array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
hs = np.hsplit(a, 2) # Split the array into 2 equal parts horizontally
hs

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [5]:
hs[0] # First part after horizontal split - index[0]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [6]:
hs[1] # Second part after horizontal split - index[1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [7]:
hs2 = np.hsplit(a, [1]) # Split the array at column index 2
hs2

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15]])]

In [8]:
# if we do it like this hs2 = np.hsplit(a, 1)
# This will split the array into 1 part, which is the original array itself
hs3 = np.hsplit(a, 1) 
hs3 

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [9]:
hs4 = np.hsplit(a, 3) # Split the array into 3 equal parts horizontally , but this will give error 
# because 4 columns cannot be evenly split into 3 parts
hs4

ValueError: array split does not result in an equal division

In [10]:
hs5 = np.hsplit(a, [1,3]) # Split the array at column indices 1 and 3
hs5 # Resulting parts after split at indices 1 and 3

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [11]:
hs6 = np.hsplit(a, [0,2,4]) # Split the array at column indices 0, 2, and 4
hs6 # Resulting parts after split at indices 0, 2, and 4

[array([], shape=(4, 0), dtype=int64),
 array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]),
 array([], shape=(4, 0), dtype=int64)]

In [12]:
hs7 = np.hsplit(a, [0,1,4]) # Split the array at column indices 0, 1, and 4
hs7 # Resulting parts after split at indices 0, 1, and 4

[array([], shape=(4, 0), dtype=int64),
 array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15]]),
 array([], shape=(4, 0), dtype=int64)]

In [13]:
hs8 = np.hsplit(a, [0,3,4]) # Split the array at column indices 0, 3, and 4
hs8 # Resulting parts after split at indices 0, 3, and 4

[array([], shape=(4, 0), dtype=int64),
 array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([], shape=(4, 0), dtype=int64)]

In [14]:
hs9 = np.hsplit(a, [2,4]) # Split the array at column indices 2 and 4
hs9 # Resulting parts after split at indices 2 and 4

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]),
 array([], shape=(4, 0), dtype=int64)]

In [15]:
hs10 = np.hsplit(a, [1,2,3]) # Split the array at column indices 1, 2, and 3` 
hs10 # Resulting parts after split at indices 1, 2, and 3

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [16]:
# hs10 a different in a way that it splits the array into 4 parts
hs11 = np.hsplit(a, [0,1,2,3,4])
hs11 # Resulting parts after split at indices 0, 1, 2, 3, and 4
# OR
hs12 = np.hsplit(a, 4) # Split the array into 4 equal parts horizontally
hs12 # Resulting 4 equal parts after horizontal split

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [17]:
# for clear understanding of hs12 
hs12

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [18]:
part1 = hs12[0] # First part
part1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [19]:
part2 = hs12[1] # Second part
part2

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [20]:
part3 = hs12[2] # Third part
part3

array([[ 2],
       [ 6],
       [10],
       [14]])

In [21]:
part4 = hs12[3] # Fourth part
part4

array([[ 3],
       [ 7],
       [11],
       [15]])

## Further Spliting the Splited matrix

In [22]:
# First part after horizontal split - index[0]
hs12[0] # First part after horizontal split - index[0]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [23]:
hs12[1] # Second part after horizontal split - index[1]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [24]:
hs12[2] # Third part after horizontal split - index[2]

array([[ 2],
       [ 6],
       [10],
       [14]])

In [25]:
hs12[3] # Fourth part after horizontal split - index[3]

array([[ 3],
       [ 7],
       [11],
       [15]])

# VERTICAL SPLIT

In [32]:
b= np.arange(36).reshape(6,6)
b # Original array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

## Vertical spliting on the basic of Parts

In [33]:
vs = np.vsplit(b, 3) # Split the array into 3 equal parts vertically
vs # Resulting 3 equal parts after vertical split

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [35]:
vs1 = np.vsplit(b, 6) # Split the array into 6 equal parts vertically
vs1 # Resulting 6 equal parts after vertical split

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35]])]

In [36]:
vs2 = np.vsplit(b,2) # Split the array into 2 equal parts vertically
vs2 # Resulting 2 equal parts after vertical split

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

## ERROR 
#### Caused due to unequal division 

In [37]:
vs3 = np.vsplit(b,4) # Split the array into 4 equal parts vertically , but this will give error
# because 6 rows cannot be evenly split into 4 parts    
vs3

ValueError: array split does not result in an equal division

## Spliting Vertically on the basic of Index

In [39]:
vs4 = np.vsplit(b,[1]) # Split the array at row index 1
vs4 # Resulting parts after split at index 1

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [40]:
vs5 = np.vsplit(b,[2]) # Split the array at row index 2
vs5 # Resulting parts after split at index 2

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [42]:
vs6 = np.vsplit(b,[3]) # Split the array at row index 3
vs6 # Resulting parts after split at index 
# Equivalent to np.vsplit(b, 2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [43]:
vs7 = np.vsplit(b,[4]) # Split the array at row index 4
vs7 # Resulting parts after split at index 4

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [44]:
vs8 = np.vsplit(b,[5]) # Split the array at row index 5
vs8 # Resulting parts after split at index 5

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35]])]

In [48]:
vs9 = np.vsplit(b,[6])
vs9 # Resulting parts after split at index 6


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]),
 array([], shape=(0, 6), dtype=int64)]

In [52]:
vs10 = np.vsplit(b,[1,3,5]) # Split the array at row indices 1, 3, and 5
vs10 # Resulting parts after split at indices 1, 3, and 5

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35]])]

In [53]:
vs11 = np.vsplit(b,[0,2,4,6]) # Split the array at row indices 0, 2, 4, and 6
vs11 # Resulting parts after split at indices 0, 2, 4,  and 6

[array([], shape=(0, 6), dtype=int64),
 array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]),
 array([], shape=(0, 6), dtype=int64)]

In [54]:
vs12 = np.vsplit(b, [2,4,6]) 
vs12 # Resulting parts after split at indices 2, 4, and 6

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]),
 array([], shape=(0, 6), dtype=int64)]

## Spliting above into more sub-divisions on indices

In [55]:
vs12[0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [56]:
vs12[1]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [57]:
vs12[2]

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [58]:
vs12[3]

array([], shape=(0, 6), dtype=int64)

In [59]:
vs7[0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [60]:
vs7[1]

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [61]:
vs7[2]

IndexError: list index out of range

In [62]:
vs6[0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [63]:
vs6[1]

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [64]:
vs6[2]

IndexError: list index out of range

In [65]:
vs5[0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [66]:
vs5[1]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [67]:
vs5[2]

IndexError: list index out of range

In [68]:
vs4[1]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [69]:
vs4[0]

array([[0, 1, 2, 3, 4, 5]])

In [70]:
vs4[2]

IndexError: list index out of range

In [71]:
vs1[0]

array([[0, 1, 2, 3, 4, 5]])

In [72]:
vs1[1]

array([[ 6,  7,  8,  9, 10, 11]])

In [73]:
vs1[2]

array([[12, 13, 14, 15, 16, 17]])

In [74]:
vs1[3]

array([[18, 19, 20, 21, 22, 23]])

In [75]:
vs1[4]

array([[24, 25, 26, 27, 28, 29]])

In [76]:
vs1[5]

array([[30, 31, 32, 33, 34, 35]])

In [77]:
vs1[6]

IndexError: list index out of range

In [78]:
vs[0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [79]:
vs[1]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [80]:
vs[2]

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [81]:
vs[3]

IndexError: list index out of range

# Shallow Copy Best Example

In [84]:
# Original array
# After all the splits original data remains same
# this is because splitting creates views of the original array without modifying it
# this is demonstrated below

b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [85]:
for i in b:
    print(i)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]
[30 31 32 33 34 35]
